[toolchain]
channel = "nightly-2023-04-25"
components = [ "clippy", "rustfmt" ]
targets = [
  "x86_64-unknown-linux-gnu",
  "x86_64-apple-darwin",
  "aarch64-apple-darwin",
  "wasm32-unknown-unknown",
]
