[package]
name = "ft-storage"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gstd.workspace = true
ft-storage-io.workspace = true
primitive-types.workspace = true
hashbrown.workspace = true

[build-dependencies]
gmeta.workspace = true
gear-wasm-builder.workspace = true
ft-storage-io.workspace = true
