[package]
name = "ft-storage"
version = "2.1.1"
edition = "2021"

[dependencies]
gstd = { git = "https://github.com/gear-tech/gear.git", rev = "5c685d0f15c412ab6ee019ceaf7ce084426dfb68" }
ft-storage-io = { path = "io" }
primitive-types = { version = "0.12", default-features = false }
hashbrown = { version = "0.13" }

[build-dependencies]
gear-wasm-builder = { git = "https://github.com/gear-tech/gear.git", rev = "5c685d0f15c412ab6ee019ceaf7ce084426dfb68" }
ft-storage-io = { path = "io" }
